# Generated by Django 2.2.2 on 2019-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOFBirth',
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
