# Generated by Django 2.2.2 on 2019-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20190701_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
