# Generated by Django 2.2.2 on 2019-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20190701_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
