# Generated by Django 2.2.2 on 2019-07-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_remove_student_studentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courseId',
            new_name='courseName',
        ),
    ]
