# Generated by Django 2.2.2 on 2019-07-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20190708_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courseName',
            new_name='courseId',
        ),
    ]
